from fastapi import APIRouter, Depends
from fastapi.responses import PlainTextResponse
from app.db import get_db
from app.security import get_current_user

router = APIRouter(prefix='/export', tags=['export'])


async def _resolve_alias(db, value: str) -> str:
    if not value or value.lower() == 'any':
        return 'any'
    alias = await db.aliases.find_one({'name': value})
    if alias:
        return ', '.join(alias.get('addresses', [])) or 'any'
    return value


def _to_nft_addr(value: str) -> str:
    if value == 'any' or not value:
        return ''
    return value


@router.get('/nftables', response_class=PlainTextResponse)
async def export_nftables(user: dict = Depends(get_current_user)):
    db = get_db()
    rules = await db.firewall_rules.find({'enabled': True}, {'_id': 0}).sort('order', 1).to_list(2000)
    nat = await db.nat_rules.find({'enabled': True}, {'_id': 0}).to_list(500)
    interfaces = await db.interfaces.find({'enabled': True}, {'_id': 0}).to_list(50)

    lines = []
    lines.append('#!/usr/sbin/nft -f')
    lines.append('# Generated by Firewall Console for Ubuntu 24')
    lines.append('# Apply with: sudo nft -f /etc/nftables.conf')
    lines.append('')
    lines.append('flush ruleset')
    lines.append('')
    lines.append('table inet firewall {')
    lines.append('    chain input {')
    lines.append('        type filter hook input priority 0; policy drop;')
    lines.append('        ct state established,related accept')
    lines.append('        iif lo accept')
    for rule in rules:
        if rule.get('direction') != 'in':
            continue
        proto = rule.get('protocol', 'any')
        action = rule.get('action', 'allow')
        nft_action = 'accept' if action == 'allow' else 'drop' if action == 'block' else 'reject'
        src = await _resolve_alias(db, rule.get('source', 'any'))
        dst_port = rule.get('destination_port', 'any')
        parts = []
        if proto != 'any':
            parts.append(proto)
        if src != 'any':
            parts.append(f'ip saddr {{ {src} }}')
        if dst_port != 'any' and proto in ('tcp', 'udp'):
            parts.append(f'dport {{ {dst_port.replace(",", ", ")} }}')
        match = ' '.join(parts) if parts else ''
        log_part = ' log prefix "[FW] "' if rule.get('log') else ''
        comment = rule.get('description', '')
        lines.append(f'        # rule[{rule["order"]}] {comment}')
        if match:
            lines.append(f'        {match}{log_part} {nft_action}')
        else:
            lines.append(f'        {nft_action}')
    lines.append('    }')
    lines.append('    chain forward {')
    lines.append('        type filter hook forward priority 0; policy drop;')
    lines.append('        ct state established,related accept')
    lines.append('    }')
    lines.append('    chain output {')
    lines.append('        type filter hook output priority 0; policy accept;')
    lines.append('    }')
    lines.append('}')
    lines.append('')
    if nat:
        lines.append('table ip nat {')
        lines.append('    chain prerouting {')
        lines.append('        type nat hook prerouting priority -100;')
        for n in nat:
            lines.append(f'        # NAT {n.get("description", "")}')
            lines.append(f'        iifname "{n["interface"].lower()}" {n["protocol"]} dport {n["external_port"]} dnat to {n["internal_ip"]}:{n["internal_port"]}')
        lines.append('    }')
        lines.append('    chain postrouting {')
        lines.append('        type nat hook postrouting priority 100;')
        for iface in interfaces:
            if iface.get('role') == 'wan':
                lines.append(f'        oifname "{iface["device"]}" masquerade')
        lines.append('    }')
        lines.append('}')
    return '\n'.join(lines) + '\n'


@router.get('/iptables', response_class=PlainTextResponse)
async def export_iptables(user: dict = Depends(get_current_user)):
    db = get_db()
    rules = await db.firewall_rules.find({'enabled': True}, {'_id': 0}).sort('order', 1).to_list(2000)
    nat = await db.nat_rules.find({'enabled': True}, {'_id': 0}).to_list(500)
    interfaces = await db.interfaces.find({'enabled': True}, {'_id': 0}).to_list(50)

    lines = []
    lines.append('#!/bin/bash')
    lines.append('# Generated by Firewall Console for Ubuntu 24')
    lines.append('# Apply with: sudo bash /tmp/firewall.sh')
    lines.append('')
    lines.append('iptables -F')
    lines.append('iptables -t nat -F')
    lines.append('iptables -P INPUT DROP')
    lines.append('iptables -P FORWARD DROP')
    lines.append('iptables -P OUTPUT ACCEPT')
    lines.append('iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT')
    lines.append('iptables -A INPUT -i lo -j ACCEPT')
    lines.append('')
    for rule in rules:
        if rule.get('direction') != 'in':
            continue
        proto = rule.get('protocol', 'any')
        action = rule.get('action', 'allow')
        target = 'ACCEPT' if action == 'allow' else 'DROP' if action == 'block' else 'REJECT'
        src = await _resolve_alias(db, rule.get('source', 'any'))
        dst_port = rule.get('destination_port', 'any')
        parts = ['iptables -A INPUT']
        if proto != 'any':
            parts.append(f'-p {proto}')
        if src != 'any' and ',' not in src:
            parts.append(f'-s {src}')
        if dst_port != 'any' and proto in ('tcp', 'udp'):
            ports_csv = dst_port.replace(' ', '')
            if ',' in ports_csv:
                parts.append(f'-m multiport --dports {ports_csv}')
            else:
                parts.append(f'--dport {ports_csv}')
        if rule.get('log'):
            parts.append(f'-j LOG --log-prefix "[FW {action}] "')
            lines.append(f'# rule[{rule["order"]}] {rule.get("description", "")}')
            lines.append(' '.join(parts))
            parts = ['iptables -A INPUT']
            if proto != 'any':
                parts.append(f'-p {proto}')
            if src != 'any' and ',' not in src:
                parts.append(f'-s {src}')
            if dst_port != 'any' and proto in ('tcp', 'udp'):
                ports_csv = dst_port.replace(' ', '')
                if ',' in ports_csv:
                    parts.append(f'-m multiport --dports {ports_csv}')
                else:
                    parts.append(f'--dport {ports_csv}')
        parts.append(f'-j {target}')
        lines.append(f'# rule[{rule["order"]}] {rule.get("description", "")}')
        lines.append(' '.join(parts))
    lines.append('')
    for n in nat:
        lines.append(f'# NAT {n.get("description", "")}')
        lines.append(f'iptables -t nat -A PREROUTING -i {n["interface"].lower()} -p {n["protocol"]} --dport {n["external_port"]} -j DNAT --to-destination {n["internal_ip"]}:{n["internal_port"]}')
    for iface in interfaces:
        if iface.get('role') == 'wan':
            lines.append(f'iptables -t nat -A POSTROUTING -o {iface["device"]} -j MASQUERADE')
    return '\n'.join(lines) + '\n'
